cache:
  document:
    max_size: 50
    ttl: 7200
  metadata:
    max_size: 200
    ttl: 86400
  response:
    enable_lru: true
    enabled: true
    max_size: 100
    ttl: 3600
error_handling:
  fallback:
    enable_cpu_fallback: true
    enable_ocr_fallback: true
    enable_simple_extraction: true
  logging:
    detailed_errors: true
    level: INFO
    max_log_size_mb: 100
    retention_days: 90
    save_error_reports: true
  retry:
    backoff_factor: 2
    max_attempts: 3
    max_wait_time: 30
experimental:
  auto_indexing: true
  conversational_mode: true
  memory_optimization: true
  progressive_loading: false
  smart_search_enhancer: true
limits:
  chunk_overlap: 200
  chunk_size: 1000
  max_pdf_pages: 10
  max_pdf_size_mb: 100
  max_search_results: 20
  max_text_length: 10000
  min_similarity_score: 0.3
  min_text_length: 10
  pdf_timeout_seconds: 30
models:
  embedding:
    device: cpu
    dimension: 768
    max_seq_length: 512
    model_name: jhgan/ko-sroberta-multitask
  qwen:
    batch_size: 512
    context_window: 8192
    gpu_layers: -1
    max_tokens: 2048
    model_file: qwen2.5-7b-instruct-q4_k_m-00001-of-00002.gguf
    name: Qwen2.5-7B
    path: models/qwen2.5-7b-instruct-q4_k_m-00001-of-00002.gguf
    temperature: 0.3
    threads: 8
    top_k: 40
    top_p: 0.95
parallel_processing:
  enabled: true
  indexing:
    batch_size: 10
    max_workers: 4
  ocr:
    max_workers: 2
    timeout_per_page: 10
  pdf:
    max_workers: 4
    page_chunk_size: 5
    timeout_per_file: 30
paths:
  cache_dir: ./.cache
  documents_dir: ./docs
  indexes_dir: ./rag_system/indexes
  logs_dir: ./logs
  models_dir: ./models
  temp_dir: ./temp
patterns:
  amount_patterns:
  - (\d{1,3}(?:,\d{3})*(?:\.\d+)?)\s*원
  - 총액\s*[:：]?\s*(\d{1,3}(?:,\d{3})*)
  - (\d+)억\s*(\d+)?만?\s*원
  - (\d+)천만\s*원
  manufacturers:
  - SONY
  - HARRIS
  - HP
  - TOSHIBA
  - PANASONIC
  - CANON
  - NIKON
  - DELL
  - APPLE
  - SAMSUNG
  - LG
  - CISCO
  - JUNIPER
  model_regex: \b[A-Z]{2,}[-\s]?\d+
performance:
  accuracy: 95%+
  avg_response_time: 0.8초
  cache_hit_rate: 45%
  total_assets: 10387
  total_documents: 63
search_modes:
  asset:
    enabled: true
    similarity_threshold: 0.85
    use_fuzzy_matching: true
  auto_detect:
    enabled: true
    keywords:
      asset:
      - 장비
      - 자산
      - 위치
      - 담당자
      - S/N
      - 시리얼
      document:
      - 기안
      - 구매
      - 계약
      - 문서
      - PDF
  document:
    bm25_weight: 0.8
    enabled: true
    use_hybrid: true
    use_reranking: true
    vector_weight: 0.2
security:
  allowed_file_types:
  - .pdf
  - .txt
  - .xlsx
  - .docx
  enable_auth: false
  max_file_upload_mb: 50
  rate_limiting:
    enabled: false
    requests_per_minute: 60
  sanitize_inputs: true
system:
  debug_mode: false
  environment: production
  name: AI-CHAT RAG System
  version: 3.2.0
ui:
  enable_feedback: true
  max_display_results: 10
  show_confidence_scores: true
  show_source_documents: true
  theme: dark
  title: AI-CHAT 통합 지식 검색 시스템
