version: '3.8'

services:
  ai-chat:
    build: .
    container_name: ai-chat-app
    ports:
      - "8501:8501"
    volumes:
      # 문서 폴더 (PDF 파일들)
      - ./docs:/app/docs
      # 데이터베이스 파일들
      - ./everything_index.db:/app/everything_index.db
      - ./metadata.db:/app/metadata.db
      # LLM 모델 파일 (크기가 크므로 볼륨 마운트)
      - ./qwen2.5-7b-instruct-q4_k_m-00001-of-00002-001.gguf:/app/qwen2.5-7b-instruct-q4_k_m-00001-of-00002-001.gguf
      # 환경 변수 파일
      - ./.env:/app/.env
      # OCR 캐시 (있는 경우)
      - ./ocr_cache:/app/ocr_cache
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    # CPU 제한 (필요시 조정)
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 2G
