# 성능 최적화 설정 (자동 생성)
# CPU: 24 cores, Memory: 4.3 GB

# 병렬 처리 설정
PARALLEL_WORKERS = 12  # CPU 코어 기반 최적값
BATCH_SIZE = 16  # 동적 배치 크기

# 캐시 설정
ENABLE_AGGRESSIVE_CACHE = True
CACHE_PRELOAD = True
CACHE_COMPRESSION = True

# OCR 병렬화
OCR_PARALLEL = True
OCR_WORKERS = 4

# 메모리 최적화
if 4.297748565673828 < 8:
    MEMORY_OPTIMIZATION = 'aggressive'
    MAX_CACHE_SIZE_MB = 500
elif 4.297748565673828 < 16:
    MEMORY_OPTIMIZATION = 'moderate'
    MAX_CACHE_SIZE_MB = 1000
else:
    MEMORY_OPTIMIZATION = 'minimal'
    MAX_CACHE_SIZE_MB = 2000

# 프리로딩 설정
PRELOAD_ON_STARTUP = False  # 백그라운드로 변경
LAZY_LOADING_ENABLED = True
PROGRESSIVE_LOADING = True

# 인덱싱 최적화
USE_INCREMENTAL_INDEXING = True
INDEX_CACHE_ENABLED = True
