[tool.ruff]
line-length = 120
preview = true
target-version = "py312"
select = ["E", "F", "I", "N", "W", "B", "Q"]
ignore = ["E501", "B008", "B905"]
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "archive",
    "build",
    "dist",
    ".eggs"
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["F401", "F811"]

[tool.black]
line-length = 120
target-version = ["py312"]
exclude = '''
/(
    \.git
  | \.venv
  | __pycache__
  | archive
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = "-v --tb=short"
