#!/bin/bash
echo '🚀 WSL to WSL 간편 이전 스크립트'
echo '================================='
echo ''
echo '옵션 1: 전체 압축 (간단함)'
echo 'tar -czf ~/ai-chat-complete.tar.gz /home/wnstn4647/AI-CHAT/'
echo '크기: 약 5.5GB, 시간: 10-15분'
echo ''
echo '옵션 2: 분할 압축 (유연함)'
echo 'cd /home/wnstn4647'
echo 'tar -czf ~/ai-chat-code.tar.gz --exclude=models --exclude=docs --exclude=__pycache__ AI-CHAT/'
echo 'tar -czf ~/ai-chat-models.tar.gz AI-CHAT/models/'
echo 'tar -czf ~/ai-chat-docs.tar.gz AI-CHAT/docs/'
echo ''
echo '새 PC WSL에서:'
echo '1. tar -xzf ai-chat-complete.tar.gz'
echo '2. cd AI-CHAT'
echo '3. python3 -m venv venv && source venv/bin/activate'
echo '4. pip install -r requirements_updated.txt'
echo '5. streamlit run web_interface.py'

