# 문서 처리 설정
# 신규 기능은 이 파일의 플래그로 ON/OFF 제어

# doctype 분류 활성화
enable_doctype_classification: true

# doctype별 처리 설정
doctype:
  # 기안서 (기본 지원)
  proposal:
    enabled: true
    keywords:
      - "기안서"
      - "장비구매"
      - "장비수리"
      - "기안자"
      - "시행일자"
      - "품의서"
    priority: 1

  # 보고서
  report:
    enabled: true
    keywords:
      - "보고서"
      - "개요"
      - "결론"
      - "결재안"
      - "검토의견"
      - "장표"
      - "그림"
    priority: 2

  # 검토서
  review:
    enabled: true
    keywords:
      - "기술검토서"
      - "검토서"
      - "검토 의견"
      - "비교표"
      - "대안"
      - "평가"
    priority: 3

  # 회의록
  minutes:
    enabled: true
    keywords:
      - "회의록"
      - "참석자"
      - "안건"
      - "결정사항"
      - "To-Do"
      - "Action Item"
      - "조치사항"
    priority: 4

# 문서 인덱싱 설정
ingestion:
  # OCR 사용 여부 (기본 OFF)
  ocr_enabled: false

  # OCR 폴백 (pdfplumber 실패 시)
  ocr_fallback: false

  # 중복 판정 기준
  dedup:
    use_hash: true  # SHA1 해시 사용
    use_normalized_filename: true  # 정규화된 파일명 사용

  # 처리 성능 설정
  performance:
    # SLA: 10건 / 60초
    batch_size: 10
    timeout_seconds: 60
    max_retries: 3

  # 파일명 규칙
  filename_pattern: "YYYY-MM-DD_제목_부가정보.pdf"

  # 로깅
  logging:
    enabled: true
    path: "logs/ingest.log"
    level: "INFO"

# 메타데이터 추출 설정
metadata:
  # 날짜 추출 우선순위
  date_priority:
    - "시행일자"
    - "기안일자"
    - "작성일자"
    - "보고일자"
    - "회의일자"

  # 작성자 추출 필드
  author_fields:
    - "기안자"
    - "작성자"
    - "보고자"
    - "검토자"

  # 부서 추출 필드
  department_fields:
    - "기안부서"
    - "소속"
    - "부서"

# 요약 템플릿 설정
summary:
  # doctype별 템플릿 활성화
  use_doctype_templates: true

  # 기본 섹션 수
  default_sections: 4

  # 최대 길이
  max_length: 2000

# 텍스트 클리닝 설정 (TextCleaner용)
text_cleaning:
  # 노이즈 패턴 (정규식)
  noise_patterns:
    # 타임스탬프 패턴
    - pattern: "(오전|오후)\\s?\\d{1,2}:\\d{2}"
      description: "프린트 타임스탬프"
    # URL 패턴
    - pattern: "(approval_form_popup\\.php\\S*|gw\\.channela-mt\\.com\\S*)"
      description: "프린트뷰 URL"
    # 페이지 번호 패턴
    - pattern: "^\\s*-\\s*\\d+\\s*-\\s*$"
      description: "페이지 번호"
      multiline: true

# 폴더 경로 설정
folders:
  incoming: "docs/incoming"
  processed: "docs/processed"
  rejected: "docs/rejected"
  quarantine: "docs/quarantine"
  extracted: "data/extracted"
