# 문서 처리 설정
# 신규 기능은 이 파일의 플래그로 ON/OFF 제어

# doctype 분류 활성화
enable_doctype_classification: true

# doctype별 처리 설정 (코퍼스 기반 보정 2025-10-27)
doctype:
  # 기안서 (기본 지원)
  proposal:
    enabled: true
    keywords:
      - "기안서"
      - "장비구매/수리"
      - "장비구매"
      - "장비수리"
      - "기안자"
      - "시행일자"
      - "품의서"
      - "구매 기안"
      - "수리 기안"
    priority: 1

  # 보고서
  report:
    enabled: true
    keywords:
      - "보고서"
      - "개요"
      - "결론"
      - "결재안"
      - "검토의견"
      - "장표"
      - "그림"
      - "분석결과"
      - "종합의견"
    priority: 2

  # 검토서
  review:
    enabled: true
    keywords:
      - "기술검토서"
      - "검토서"
      - "검토의 건"
      - "검토 의견"
      - "비교표"
      - "비교검토"
      - "대안"
      - "평가"
      - "적합성"
    priority: 3

  # 회의록
  minutes:
    enabled: true
    keywords:
      - "회의록"
      - "참석자"
      - "안건"
      - "결정사항"
      - "To-Do"
      - "Action Item"
      - "조치사항"
      - "협의내용"
    priority: 4

  # 폐기/처분 문서 (실측 추가)
  disposal:
    enabled: true
    keywords:
      - "폐기"
      - "불용"
      - "처분"
      - "폐기 요청"
      - "불용장비"
    priority: 5

# 문서 인덱싱 설정
ingestion:
  # OCR 사용 여부 (기본 OFF)
  ocr_enabled: false

  # OCR 폴백 (pdfplumber 실패 시)
  ocr_fallback: false

  # 중복 판정 기준
  dedup:
    use_hash: true  # SHA1 해시 사용
    use_normalized_filename: true  # 정규화된 파일명 사용

  # 처리 성능 설정
  performance:
    # SLA: 10건 / 60초
    batch_size: 10
    timeout_seconds: 60
    max_retries: 3

  # 파일명 규칙
  filename_pattern: "YYYY-MM-DD_제목_부가정보.pdf"

  # 로깅
  logging:
    enabled: true
    path: "logs/ingest.log"
    level: "INFO"

# 메타데이터 추출 설정
metadata:
  # 날짜 추출 우선순위
  date_priority:
    - "시행일자"
    - "기안일자"
    - "작성일자"
    - "보고일자"
    - "회의일자"

  # 작성자 추출 필드
  author_fields:
    - "기안자"
    - "작성자"
    - "보고자"
    - "검토자"

  # 부서 추출 필드
  department_fields:
    - "기안부서"
    - "소속"
    - "부서"

# 요약 템플릿 설정
summary:
  # doctype별 템플릿 활성화
  use_doctype_templates: true

  # 기본 섹션 수
  default_sections: 4

  # 최대 길이
  max_length: 2000

# 표 파싱 설정 (비용표 등)
table_parsing:
  # 헤더 패턴 (표 감지용 - regex)
  header_patterns:
    - "품명.*수량.*단가.*금액"
    - "품목.*개수.*금액"
    - "내역.*수량.*단가.*합계"
    - "품명.*단가.*합계"
    - "품목.*금액"
    - "모델.*수량.*단가.*합계"  # 모델명 (합계)
    - "모델.*수량.*단가.*금액"  # 모델명 (금액)
    - "모델.*내역.*단가"

  # 숫자 정규화 설정
  number_normalization:
    remove_chars:
      - ","      # 천 단위 구분자
      - "₩"      # 원화 기호
      - "원"     # 한글 원
      - "won"    # 영문 원
      - " "      # 공백

  # 합계 검증 설정
  sum_validation:
    tolerance: 1  # ±1원 허용 (반올림 오차)

  # 비용표 헤더 별칭 (코퍼스 실측)
  cost_table_headers:
    item_aliases:
      - "품명"
      - "품목"
      - "내역"
      - "구매품목"
      - "수리항목"
    quantity_aliases:
      - "수량"
      - "개수"
      - "ea"
      - "EA"
    unit_price_aliases:
      - "단가"
      - "금액"
      - "가격"
    total_aliases:
      - "합계"
      - "총계"
      - "금액합계"
      - "총액"
      - "소계"
    vat_aliases:
      - "VAT"
      - "부가세"
      - "부가가치세"

# 텍스트 클리닝 설정 (TextCleaner용)
text_cleaning:
  # 노이즈 패턴 (정규식) - 코퍼스 기반 보정 (2025-10-27)
  noise_patterns:
    # 타임스탬프 패턴 (확장: 날짜.시간 형식 포함)
    - pattern: "\\b\\d{1,2}\\.\\s*\\d{1,2}\\.\\s*\\d{1,2}\\.\\s*(오전|오후)\\s*\\d{1,2}:\\d{2}\\b"
      description: "프린트 타임스탬프 (날짜 포함)"
    - pattern: "(오전|오후)\\s?\\d{1,2}:\\d{2}"
      description: "프린트 타임스탬프 (시간만)"

    # 그룹웨어 URL 패턴
    - pattern: "gw\\.channela-mt\\.com/\\S+"
      description: "그룹웨어 도메인 URL"
    - pattern: "approval_form_popup\\.php\\S*"
      description: "결재 팝업 스크립트"

    # 페이지 번호 패턴
    - pattern: "^\\s*-\\s*\\d+\\s*-\\s*$"
      description: "페이지 번호"
      multiline: true

    # 반복 헤더 제거 (코퍼스 실측)
    - pattern: "^(장비구매/수리\\s*기안서|기안서)\\s*$"
      description: "반복되는 문서 제목"
      multiline: true

    # 섹션 앵커 (단독 라인으로 나타나는 경우 제거)
    - pattern: "^(개요|내용|신청수량|수령인|비고|수리\\s*내용|발생\\s*비용|구매\\s*내용|비교검토|기술\\s*검토|별도\\s*첨부)\\s*$"
      description: "단독 섹션 앵커"
      multiline: true

# 폴더 경로 설정
folders:
  incoming: "docs/incoming"
  processed: "docs/processed"
  rejected: "docs/rejected"
  quarantine: "docs/quarantine"
  extracted: "data/extracted"
